services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-shopee
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - shopee-network

networks:
  shopee-network:
    external: true
