services:
  frontend-shopee:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3002
    ports:
      - "5174:80"
    networks:
      - frontend-shopee-network

networks:
  frontend-shopee-network:
