services:
  backend-shopee:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      db-shopee:
        condition: service_healthy
    networks:
      - backend-shopee-network

  db-shopee:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - shopee-backend-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-shopee-network

networks:
  backend-shopee-network:

volumes:
  shopee-backend-db-data:
