export const API_URL = process.env.NEXT_PUBLIC_BASE_URL;

export const searchRecommendations = [
  "Parfum YSL",
  "Jersey Argentina Home 26",
  "New Balance 530 Navy White",
  "Tumbler Tahan Panas dan Dingin",
  "Jeans Levis 501",
  "La Roche Posay",
  "Amaterasun Serum",
  "Sepatu Converse",
  "Kemeja Flanel Pria",
  "Tas Ransel Anti Air",
  "Sepatu Nike Air Force 1",
  "Jersey Manchester United Home 25/26",
  "Adidas Samba OG",
  "Kaos Polos Cotton Combed 30s",
  "Celana Chino Pria Slim Fit",
  "Hoodie Oversize Unisex",
  "Skincare Set Somethinc",
  "Sunscreen Skintific SPF 50",
  "Serum Niacinamide Wardah",
  "Parfum Zara Man",
  "Parfum Dior Sauvage",
  "Sepatu Vans Old Skool",
  "Sepatu Sneakers Compass",
  "Tas Selempang Pria Eiger",
  "Tas Wanita Charles Keith",
  "Dompet Kulit Pria",
  "Jaket Bomber Pria",
  "Jaket Parka Winter",
  "Kemeja Batik Pria",
  "Kaos Kaki Bundling 5 Pasang",
  "Sandal Jepit Swallow",
  "Sandal Gunung Eiger",
  "Topi Baseball Cap Polos",
  "Kacamata Hitam Pria Wanita",
  "Jam Tangan Digital Casio",
  "Jam Tangan Fossil Original",
  "Powerbank 20000mAh Fast Charging",
  "Kabel Data USB Type C",
  "Earphone Bluetooth TWS",
  "Headset Gaming JBL",
  "Charger Iphone Original",
  "Case Iphone 15 Pro Max",
  "Tempered Glass Samsung S24",
  "Ring Light Tripod HP",
  "Mouse Wireless Logitech",
  "Keyboard Mechanical Gaming",
  "Flashdisk 64GB Sandisk",
  "Hardisk Eksternal 1TB",
  "Kabel HDMI 2 Meter",
  "Blender Portable USB",
  "Air Fryer Low Watt",
  "Rice Cooker Mini 1 Liter",
  "Dispenser Galon Bawah",
  "Setrika Uap Philips",
  "Vacuum Cleaner Mini",
  "Kipas Angin Portable",
  "Lampu Tidur LED",
  "Lampu Emergency Serbaguna",
  "Tumbler Stainless 1 Liter",
  "Botol Minum Anak Karakter",
  "Kotak Makan Bekal Anak",
  "Termos Nasi Stainless",
  "Talenan Kayu Antibakteri",
  "Pisau Dapur Set Stainless",
  "Panci Set Anti Lengket",
  "Wajan Granite Coating",
  "Rak Piring Serbaguna",
  "Organizer Lemari Baju",
  "Gantungan Baju Anti Slip",
  "Keset Kaki Microfiber",
  "Sprei Set Katun Jepang",
  "Bantal Leher Travel",
  "Guling Anak Karakter",
  "Selimut Bulu Halus",
  "Handuk Microfiber Quick Dry",
  "Karpet Bulu Ruang Tamu",
  "Tirai Jendela Blackout",
  "Rak Sepatu Lipat",
  "Kursi Gaming Ergonomis",
  "Meja Lipat Laptop",
  "Kasur Lipat Busa",
  "Cermin Rias LED",
  "Sikat Gigi Elektrik",
  "Hair Dryer Mini Portable",
  "Catokan Rambut 2in1",
  "Vitamin C Tablet Isap",
  "Masker Medis 3 Ply",
  "Hand Sanitizer Gel 500ml",
  "Minyak Kayu Putih Cap Lang",
  "Susu UHT Full Cream 1 Liter",
  "Kopi Sachet Kemasan Box",
  "Madu Hutan Asli 500gr",
  "Snack Kentang Kekinian",
  "Beras Premium 5kg",
  "Minyak Goreng Kemasan 2L",
  "Sabun Cuci Piring Refill",
  "Deterjen Cair Konsentrat",
  "Pewangi Pakaian Sekali Bilas",
  "Tisu Basah Bayi",
  "Popok Bayi Ukuran M",
  "Mainan Edukasi Anak Kayu",
  "Sepeda Lipat Dewasa",
  "Matras Yoga Anti Slip",
  "Dumbbell Set 5kg",
  "Sepatu Lari Running Pria",
];

export function getItemRandomly(arr: string[], count: number): string[] {
  const shuffled = [...arr].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

export const bannerMenuLinks = [
  {
    name: "Shopee Pilh Lokal",
    link: "/shopee-pilih-lokal",
    image: "/images/mainpage/bannerDanMenu/shopee-pilih-lokal.webp",
  },
  {
    name: "Shopee Mall",
    link: "/shopee-mall",
    image: "/images/mainpage/bannerDanMenu/shopee-mall.webp",
  },
  {
    name: "Pulsa & Tagihan",
    link: "/pulsa-dan-tagihan",
    image: "/images/mainpage/bannerDanMenu/pulsa-dan-tagihan.webp",
  },
  {
    name: "Flash Sale",
    link: "/flash-sale",
    image: "/images/mainpage/bannerDanMenu/flash-sale.webp",
  },
  {
    name: "Shopee Supermarket",
    link: "/shopee-supermarket",
    image: "/images/mainpage/bannerDanMenu/shopee-supermarket.webp",
  },
  {
    name: "Dikelola Shopee",
    link: "/dikelola-shopee",
    image: "/images/mainpage/bannerDanMenu/dikelola-shopee.webp",
  },
  {
    name: "Fitcheck Diskon 25%",
    link: "/fitcheck-diskon-25",
    image: "/images/mainpage/bannerDanMenu/fitcheck-diskon-25.webp",
  },
  {
    name: "Gratis Ongkir dan Voucher",
    link: "/gratis-ongkir-dan-voucher",
    image: "/images/mainpage/bannerDanMenu/gratis-ongkir-dan-voucher.webp",
  },
  {
    name: "Shopee Barokah",
    link: "/shopee-barokah",
    image: "/images/mainpage/bannerDanMenu/shopee-barokah.webp",
  },
  {
    name: "Semua Promo",
    link: "/semua-promo",
    image: "/images/mainpage/bannerDanMenu/semua-promo.webp",
  },
];

export const imageBannerBesar = {
  name: "Shopee Pilih Lokal",
  link: "/shopee-pilih-lokal-banner",
  image: "/images/mainpage/bannerDanMenu/shopee-pilih-lokal-banner.webp",
};

export const imageBannerKecil = [
  {
    name: "Shopee Mall 100% ORI",
    link: "/shopee-mall-100-ori-banner",
    image: "/images/mainpage/bannerDanMenu/shopee-mall-100-ori-banner.webp",
  },
  {
    name: "Shopee Barokah",
    link: "/shopee-barokah-banner",
    image: "/images/mainpage/bannerDanMenu/shopee-barokah-banner.webp",
  },
];
