import { FlashSaleItem, menuLinks, TimeLeftFlashSale } from "../type/type";

export const API_URL = process.env.NEXT_PUBLIC_BASE_URL;

export const searchRecommendations = [
  "Parfum YSL",
  "Jersey Argentina Home 26",
  "New Balance 530 Navy White",
  "Tumbler Tahan Panas dan Dingin",
  "Jeans Levis 501",
  "La Roche Posay",
  "Amaterasun Serum",
  "Sepatu Converse",
  "Kemeja Flanel Pria",
  "Tas Ransel Anti Air",
  "Sepatu Nike Air Force 1",
  "Jersey Manchester United Home 25/26",
  "Adidas Samba OG",
  "Kaos Polos Cotton Combed 30s",
  "Celana Chino Pria Slim Fit",
  "Hoodie Oversize Unisex",
  "Skincare Set Somethinc",
  "Sunscreen Skintific SPF 50",
  "Serum Niacinamide Wardah",
  "Parfum Zara Man",
  "Parfum Dior Sauvage",
  "Sepatu Vans Old Skool",
  "Sepatu Sneakers Compass",
  "Tas Selempang Pria Eiger",
  "Tas Wanita Charles Keith",
  "Dompet Kulit Pria",
  "Jaket Bomber Pria",
  "Jaket Parka Winter",
  "Kemeja Batik Pria",
  "Kaos Kaki Bundling 5 Pasang",
  "Sandal Jepit Swallow",
  "Sandal Gunung Eiger",
  "Topi Baseball Cap Polos",
  "Kacamata Hitam Pria Wanita",
  "Jam Tangan Digital Casio",
  "Jam Tangan Fossil Original",
  "Powerbank 20000mAh Fast Charging",
  "Kabel Data USB Type C",
  "Earphone Bluetooth TWS",
  "Headset Gaming JBL",
  "Charger Iphone Original",
  "Case Iphone 15 Pro Max",
  "Tempered Glass Samsung S24",
  "Ring Light Tripod HP",
  "Mouse Wireless Logitech",
  "Keyboard Mechanical Gaming",
  "Flashdisk 64GB Sandisk",
  "Hardisk Eksternal 1TB",
  "Kabel HDMI 2 Meter",
  "Blender Portable USB",
  "Air Fryer Low Watt",
  "Rice Cooker Mini 1 Liter",
  "Dispenser Galon Bawah",
  "Setrika Uap Philips",
  "Vacuum Cleaner Mini",
  "Kipas Angin Portable",
  "Lampu Tidur LED",
  "Lampu Emergency Serbaguna",
  "Tumbler Stainless 1 Liter",
  "Botol Minum Anak Karakter",
  "Kotak Makan Bekal Anak",
  "Termos Nasi Stainless",
  "Talenan Kayu Antibakteri",
  "Pisau Dapur Set Stainless",
  "Panci Set Anti Lengket",
  "Wajan Granite Coating",
  "Rak Piring Serbaguna",
  "Organizer Lemari Baju",
  "Gantungan Baju Anti Slip",
  "Keset Kaki Microfiber",
  "Sprei Set Katun Jepang",
  "Bantal Leher Travel",
  "Guling Anak Karakter",
  "Selimut Bulu Halus",
  "Handuk Microfiber Quick Dry",
  "Karpet Bulu Ruang Tamu",
  "Tirai Jendela Blackout",
  "Rak Sepatu Lipat",
  "Kursi Gaming Ergonomis",
  "Meja Lipat Laptop",
  "Kasur Lipat Busa",
  "Cermin Rias LED",
  "Sikat Gigi Elektrik",
  "Hair Dryer Mini Portable",
  "Catokan Rambut 2in1",
  "Vitamin C Tablet Isap",
  "Masker Medis 3 Ply",
  "Hand Sanitizer Gel 500ml",
  "Minyak Kayu Putih Cap Lang",
  "Susu UHT Full Cream 1 Liter",
  "Kopi Sachet Kemasan Box",
  "Madu Hutan Asli 500gr",
  "Snack Kentang Kekinian",
  "Beras Premium 5kg",
  "Minyak Goreng Kemasan 2L",
  "Sabun Cuci Piring Refill",
  "Deterjen Cair Konsentrat",
  "Pewangi Pakaian Sekali Bilas",
  "Tisu Basah Bayi",
  "Popok Bayi Ukuran M",
  "Mainan Edukasi Anak Kayu",
  "Sepeda Lipat Dewasa",
  "Matras Yoga Anti Slip",
  "Dumbbell Set 5kg",
  "Sepatu Lari Running Pria",
];

export const bannerMenuLinks: menuLinks[] = [
  {
    name: "Shopee Pilh Lokal",
    link: "/shopee-pilih-lokal",
    image: "/images/mainpage/bannerDanMenu/shopee-pilih-lokal.webp",
  },
  {
    name: "Shopee Mall",
    link: "/shopee-mall",
    image: "/images/mainpage/bannerDanMenu/shopee-mall.webp",
  },
  {
    name: "Pulsa & Tagihan",
    link: "/pulsa-dan-tagihan",
    image: "/images/mainpage/bannerDanMenu/pulsa-dan-tagihan.webp",
  },
  {
    name: "Flash Sale",
    link: "/flash-sale",
    image: "/images/mainpage/bannerDanMenu/flash-sale.webp",
  },
  {
    name: "Shopee Supermarket",
    link: "/shopee-supermarket",
    image: "/images/mainpage/bannerDanMenu/shopee-supermarket.webp",
  },
  {
    name: "Dikelola Shopee",
    link: "/dikelola-shopee",
    image: "/images/mainpage/bannerDanMenu/dikelola-shopee.webp",
  },
  {
    name: "Fitcheck Diskon 25%",
    link: "/fitcheck-diskon-25",
    image: "/images/mainpage/bannerDanMenu/fitcheck-diskon-25.webp",
  },
  {
    name: "Gratis Ongkir dan Voucher",
    link: "/gratis-ongkir-dan-voucher",
    image: "/images/mainpage/bannerDanMenu/gratis-ongkir-dan-voucher.webp",
  },
  {
    name: "Shopee Barokah",
    link: "/shopee-barokah",
    image: "/images/mainpage/bannerDanMenu/shopee-barokah.webp",
  },
  {
    name: "Semua Promo",
    link: "/semua-promo",
    image: "/images/mainpage/bannerDanMenu/semua-promo.webp",
  },
];

export const imageBannerBesar: menuLinks = {
  name: "Shopee Pilih Lokal",
  link: "/shopee-pilih-lokal-banner",
  image: "/images/mainpage/bannerDanMenu/shopee-pilih-lokal-banner.webp",
};

export const imageBannerKecil: menuLinks[] = [
  {
    name: "Shopee Mall 100% ORI",
    link: "/shopee-mall-100-ori-banner",
    image: "/images/mainpage/bannerDanMenu/shopee-mall-100-ori-banner.webp",
  },
  {
    name: "Shopee Barokah",
    link: "/shopee-barokah-banner",
    image: "/images/mainpage/bannerDanMenu/shopee-barokah-banner.webp",
  },
];

export const kategoriMenuLists: menuLinks[] = [
  {
    name: "Elektronik",
    link: "/kategori/elektronik",
    image: "/images/mainpage/kategori/elektronik.webp",
  },
  {
    name: "Komputer & Aksesoris",
    link: "/kategori/komputer-dan-aksesoris",
    image: "/images/mainpage/kategori/komputerDanAksesoris.webp",
  },
  {
    name: "Handphone & Aksesoris",
    link: "/kategori/handphone-dan-aksesoris",
    image: "/images/mainpage/kategori/handphoneDanAksesoris.webp",
  },
  {
    name: "Pakaian Pria",
    link: "/kategori/pakaian-pria",
    image: "/images/mainpage/kategori/pakaianPria.webp",
  },
  {
    name: "Sepatu Pria",
    link: "/kategori/sepatu-pria",
    image: "/images/mainpage/kategori/sepatuPria.webp",
  },
  {
    name: "Tas Pria",
    link: "/kategori/tas-pria",
    image: "/images/mainpage/kategori/tasPria.webp",
  },
  {
    name: "Aksesoris Fashion",
    link: "/kategori/aksesoris-fashion",
    image: "/images/mainpage/kategori/aksesorisFashion.webp",
  },
  {
    name: "Jam Tangan",
    link: "/kategori/jam-tangan",
    image: "/images/mainpage/kategori/jamTangan.webp",
  },
  {
    name: "Kesehatan",
    link: "/kategori/kesehatan",
    image: "/images/mainpage/kategori/kesehatan.webp",
  },
  {
    name: "Hobi & Koleksi",
    link: "/kategori/hobi-dan-koleksi",
    image: "/images/mainpage/kategori/hobiDanKoleksi.webp",
  },
  {
    name: "Olahraga & Outdoor",
    link: "/kategori/olahraga-dan-outdoor",
    image: "/images/mainpage/kategori/olahragaDanOutdoor.webp",
  },
  {
    name: "Souvenir & Perlengkapan",
    link: "/kategori/souvenir-dan-perlengkapan",
    image: "/images/mainpage/kategori/souvenirDanPerlengkapan.webp",
  },
  {
    name: "Voucher",
    link: "/kategori/voucher",
    image: "/images/mainpage/kategori/voucher.webp",
  },
  {
    name: "Makanan & Minuman",
    link: "/kategori/makanan-dan-minuman",
    image: "/images/mainpage/kategori/makananDanMinuman.webp",
  },
  {
    name: "Perawatan & Kecantikan",
    link: "/kategori/perawatan-dan-kecantikan",
    image: "/images/mainpage/kategori/perawatanDanKecantikan.webp",
  },
  {
    name: "Perlengkapan Rumah",
    link: "/kategori/perlengkapan-rumah",
    image: "/images/mainpage/kategori/perlengkapanRumah.webp",
  },
  {
    name: "Pakaian Wanita",
    link: "/kategori/pakaian-wanita",
    image: "/images/mainpage/kategori/pakaianWanita.webp",
  },
  {
    name: "Fashion Muslim",
    link: "/kategori/fashion-muslim",
    image: "/images/mainpage/kategori/fashionMuslim.webp",
  },
  {
    name: "Fashion Bayi & Anak",
    link: "/kategori/fashion-bayi-dan-anak",
    image: "/images/mainpage/kategori/fashionBayiDanAnak.webp",
  },
  {
    name: "Ibu & Bayi",
    link: "/kategori/ibu-dan-bayi",
    image: "/images/mainpage/kategori/ibuDanBayi.webp",
  },
  {
    name: "Sepatu Wanita",
    link: "/kategori/sepatu-wanita",
    image: "/images/mainpage/kategori/sepatuWanita.webp",
  },
  {
    name: "Tas Wanita",
    link: "/kategori/tas-wanita",
    image: "/images/mainpage/kategori/tasWanita.webp",
  },
  {
    name: "Otomotif",
    link: "/kategori/otomotif",
    image: "/images/mainpage/kategori/otomotif.webp",
  },
  {
    name: "Buku & Alat Tulis",
    link: "/kategori/buku-dan-alat-tulis",
    image: "/images/mainpage/kategori/bukuDanAlatTulis.webp",
  },
  {
    name: "Fotografi",
    link: "/kategori/fotografi",
    image: "/images/mainpage/kategori/fotografi.webp",
  },
  {
    name: "Deals Sekitarmu",
    link: "/kategori/deals-sekitarmu",
    image: "/images/mainpage/kategori/dealsSekitarmu.webp",
  },
];

export const flashSaleEndTime = new Date("2026-07-23T23:59:59"); // Set the end time for the flash sale

export const flashSaleLists: FlashSaleItem[] = [
  {
    id: "fs-001",
    name: "EON Cahaya Putih 12 Watt Lampu LED Hemat Energi",
    image:
      "https://down-id.img.susercontent.com/file/id-11134207-822wu-mooy98tuku8bd9@resize_w450_nl.webp",
    price: 108500,
    originalPrice: 175000,
    discountPercent: 38,
    isMall: true,
    isOri: true,
    stockSold: 187,
    stockTotal: 250,
    link: "/produk/eon-lampu-led-12w",
  },
  {
    id: "fs-002",
    name: "ISKU S2 Kunci L 9 Pcs ABS Material Box Brand Choice",
    image:
      "https://down-id.img.susercontent.com/file/id-11134207-822wu-mooy98tuku8bd9@resize_w450_nl.webp",
    price: 67100,
    originalPrice: 98700,
    discountPercent: 32,
    isMall: true,
    isOri: true,
    stockSold: 342,
    stockTotal: 400,
    link: "/produk/isku-kunci-l-set",
  },
  {
    id: "fs-003",
    name: "EON Pure 15 Watt Lampu LED Cahaya Putih",
    image: "/images/products/lampu-eon-pure-15w.png",
    price: 102000,
    originalPrice: 188900,
    discountPercent: 46,
    isMall: false,
    isOri: true,
    stockSold: 95,
    stockTotal: 300,
    link: "/produk/eon-pure-lampu-led-15w",
  },
  {
    id: "fs-004",
    name: "Kunci Sock Set 121 PC 72 Gigi Perkakas Bengkel Lengkap",
    image: "/images/products/kunci-sock-set-121pc.png",
    price: 647900,
    originalPrice: 696700,
    discountPercent: 7,
    isMall: true,
    isOri: true,
    stockSold: 41,
    stockTotal: 150,
    link: "/produk/kunci-sock-set-121pc",
  },
  {
    id: "fs-005",
    name: "Mesin Gerinda Tangan Isku Daya Super Kuat Garansi 1 Tahun",
    image: "/images/products/gerinda-isku.png",
    price: 240900,
    originalPrice: 501900,
    discountPercent: 52,
    isMall: true,
    isOri: false,
    stockSold: 278,
    stockTotal: 300,
    link: "/produk/mesin-gerinda-isku",
  },
  {
    id: "fs-006",
    name: "Semprotan Cat Elektrik 1000ML Atomisasi Tinggi",
    image: "/images/products/semprotan-cat-elektrik.png",
    price: 314500,
    originalPrice: 669200,
    discountPercent: 53,
    isMall: false,
    isOri: true,
    stockSold: 133,
    stockTotal: 200,
    link: "/produk/semprotan-cat-elektrik",
  },
  {
    id: "fs-007",
    name: "Serum Wajah Niacinamide 10% + Zinc Brightening 30ml",
    image: "/images/products/serum-niacinamide.png",
    price: 45900,
    originalPrice: 89000,
    discountPercent: 48,
    isMall: true,
    isOri: true,
    stockSold: 512,
    stockTotal: 600,
    link: "/produk/serum-niacinamide-zinc",
  },
  {
    id: "fs-008",
    name: "Kaos Polos Oversize Cotton Combed 30s Unisex",
    image: "/images/products/kaos-oversize-polos.png",
    price: 39000,
    originalPrice: 65000,
    discountPercent: 40,
    isMall: false,
    isOri: true,
    stockSold: 89,
    stockTotal: 500,
    link: "/produk/kaos-oversize-cotton-combed",
  },
  {
    id: "fs-009",
    name: "Power Bank 20000mAh Fast Charging 22.5W Dual USB",
    image: "/images/products/powerbank-20000mah.png",
    price: 129000,
    originalPrice: 259000,
    discountPercent: 50,
    isMall: true,
    isOri: true,
    stockSold: 421,
    stockTotal: 450,
    link: "/produk/powerbank-20000mah-fast-charging",
  },
  {
    id: "fs-010",
    name: "Rak Sepatu Lipat 3 Susun Plastik Anti Debu",
    image: "/images/products/rak-sepatu-lipat.png",
    price: 55000,
    originalPrice: 95000,
    discountPercent: 42,
    isMall: false,
    isOri: false,
    stockSold: 67,
    stockTotal: 200,
    link: "/produk/rak-sepatu-lipat-3-susun",
  },
  {
    id: "fs-011",
    name: "Botol Minum Tumbler Stainless Steel 1 Liter Tahan Panas Dingin",
    image: "/images/products/tumbler-stainless-1l.png",
    price: 48500,
    originalPrice: 110000,
    discountPercent: 56,
    isMall: true,
    isOri: true,
    stockSold: 298,
    stockTotal: 350,
    link: "/produk/tumbler-stainless-1-liter",
  },
  {
    id: "fs-012",
    name: "Mainan Edukasi Anak Puzzle Kayu Balok Angka Huruf",
    image: "/images/products/puzzle-kayu-edukasi.png",
    price: 32000,
    originalPrice: 60000,
    discountPercent: 47,
    isMall: false,
    isOri: true,
    stockSold: 154,
    stockTotal: 250,
    link: "/produk/puzzle-kayu-edukasi-anak",
  },
  {
    id: "fs-013",
    name: "Karpet Rumah Tangga Bulu Rasfur Anti Slip 80x120cm",
    image: "/images/products/karpet-bulu-rasfur.png",
    price: 75000,
    originalPrice: 149000,
    discountPercent: 50,
    isMall: true,
    isOri: true,
    stockSold: 203,
    stockTotal: 220,
    link: "/produk/karpet-bulu-rasfur-anti-slip",
  },
  {
    id: "fs-014",
    name: "Helm Half Face SNI Double Visor Anti UV",
    image: "/images/products/helm-half-face-sni.png",
    price: 185000,
    originalPrice: 320000,
    discountPercent: 42,
    isMall: true,
    isOri: true,
    stockSold: 76,
    stockTotal: 180,
    link: "/produk/helm-half-face-sni-double-visor",
  },
  {
    id: "fs-015",
    name: "Celana Perempuan Kekinian High Waist Bahan Katun Stretch",
    image: "/images/products/celana-highwaist-katun.png",
    price: 58000,
    originalPrice: 110000,
    discountPercent: 47,
    isMall: false,
    isOri: true,
    stockSold: 312,
    stockTotal: 400,
    link: "/produk/celana-highwaist-katun-stretch",
  },
];

export function calculateTimeLeft(endTime: Date): TimeLeftFlashSale {
  let difference = endTime.getTime() - new Date().getTime();

  if (difference <= 0) {
    return {
      hours: 0,
      minutes: 0,
      seconds: 0,
      isExpired: true,
    };
  }

  let hours = Math.floor(difference / (1000 * 60 * 60));
  let minutes = Math.floor((difference / (1000 * 60)) % 60);
  let seconds = Math.floor((difference / 1000) % 60);

  return {
    hours,
    minutes,
    seconds,
    isExpired: false,
  };
}

export function pad(num: number) {
  return String(num).padStart(2, "0");
}

export function formatRupiah(amount: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
  }).format(amount);
}
